feat(tests): Again some tests

diff --git a/runTests b/runTests
--- a/runTests
+++ b/runTests
@@ -4,6 +4,17 @@ GREEN="\e[32m"
 ITALICRED="\e[3;${RED}m"
 ENDCOLOR="\e[0m"
 
+./compile
+
+java -cp $PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin/ org.junit.runner.JUnitCore tests.AllTests
+
+if (( $? != 0 )); then
+    echo -en "\n"
+    echo -en "${RED}Junit tests failed${ENDCOLOR}"
+    exit 1
+else 
+    echo -e "${GREEN}All JUnit tests passed${ENDCOLOR}\n"
+fi
 
 test_cases=(
     "-mess 101001101"
@@ -74,6 +85,9 @@ test_cases=(
     "-mess 100 -seed 1308 -form NRZ -snrpb 5f"
     "-mess 100 -seed 1308 -form NRZ -snrpb 3f -nbEch 100"
     "-mess 100 -seed 1308 -form NRZ -snrpb 5f -nbEch 100"
+    "-mess 10 -seed 1308 -form RZ -snrpb -20f -nbEch 100 -s"
+    "-mess 10 -seed 1308 -form RZ -snrpb -5f -nbEch 100 -s"
+    "-mess 10 -seed 1308 -form RZ -snrpb 0f -nbEch 100 -s"
 )
 cpt=0
 for cmd in "${test_cases[@]}"; do
@@ -90,10 +104,3 @@ if (( $cpt != 0 )); then
 fi
 
 echo -e "${GREEN}All tests passed${ENDCOLOR}\n"
-java -cp $PWD/lib/hamcrest-core-1.3.jar:$PWD/lib/junit-4.13.2.jar:$PWD/bin/ org.junit.runner.JUnitCore tests.AllTests
-
-if (( $cpt != 0 )); then
-    echo -en "\n"
-    echo -en "${RED}Junit tests failed${ENDCOLOR}"
-    exit 1
-fi
